// Generator kerangka slide mock untuk AI Stage 1
// Menghasilkan daftar slide outline cerdas berdasarkan template dan data kontekstual

export const CANONICAL_LAYOUTS = [
  { id: 'title_slide', name: 'Hero Cover', badge: 'Hero Cover' },
  { id: 'two_column', name: 'Dua Kolom', badge: 'Dua Kolom' },
  { id: 'metrics_grid', name: 'Grid 4 Metrik', badge: 'Grid 4 Metrik' },
  { id: 'card_grid', name: 'Bento Cards', badge: 'Bento Cards' },
  { id: 'title_bullets', name: 'Grafik / Poin Finansial', badge: 'Grafik Finansial' },
  { id: 'contact_closing', name: 'Call to Action', badge: 'Call to Action' },
];

export function generateMockOutline(templateId, structuredData = {}, rawContext = '') {
  const company = structuredData.companyName || structuredData.productName || 'Usaha Anda';
  const period = structuredData.reportPeriod || 'Q1 2026';

  switch (templateId) {
    case 'penawaran_produk':
      return [
        {
          id: 'slide-1',
          slideNumber: 1,
          title: `Penawaran Eksklusif Katalog ${structuredData.productName || 'Produk Unggulan'}`,
          objective: 'Menyajikan identitas produk utama dan kesan profesional awal',
          suggestedLayout: 'Hero Cover',
          layoutType: 'title_slide',
          isEdited: false,
        },
        {
          id: 'slide-2',
          slideNumber: 2,
          title: 'Latar Belakang Pasar & Keunggulan Produk',
          objective: 'Menjelaskan problem di pasar dan diferensiasi produk kami',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-3',
          slideNumber: 3,
          title: 'Spesifikasi, Komposisi & Varian SKU',
          objective: 'Rincian detail teknis produk, varian kemasan dan standar mutu',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-4',
          slideNumber: 4,
          title: `Skema Harga, MOQ ${structuredData.moq ? `(${structuredData.moq} pcs)` : ''} & Margin Reseller`,
          objective: 'Transparansi struktur harga, minimum kuantiti order, dan margin keuntungan',
          suggestedLayout: 'Grid 4 Metrik',
          layoutType: 'metrics_grid',
          isEdited: false,
        },
        {
          id: 'slide-5',
          slideNumber: 5,
          title: 'Kapasitas Pasokan & Jaminan Kualitas Produk',
          objective: 'Menunjukkan kesiapan produksi skala besar dan sertifikasi legalitas',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-6',
          slideNumber: 6,
          title: 'Dukungan Promosi & Fasilitas untuk Mitra',
          objective: 'Materi marketing, katalog digital, dan bantuan onboarding reseller',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-7',
          slideNumber: 7,
          title: 'Simulasi Potensi Omzet & Profit Mitra',
          objective: 'Proyeksi pendapatan bulanan mitra berdasarkan skema reseller',
          suggestedLayout: 'Grafik Finansial',
          layoutType: 'title_bullets',
          isEdited: false,
        },
        {
          id: 'slide-8',
          slideNumber: 8,
          title: 'Alur Pemesanan & Kontak Tim Penjualan',
          objective: 'Instruksi langkah order awal dan saluran komunikasi resmi',
          suggestedLayout: 'Call to Action',
          layoutType: 'contact_closing',
          isEdited: false,
        },
      ];

    case 'proposal_kerjasama':
      return [
        {
          id: 'slide-1',
          slideNumber: 1,
          title: `Proposal Kemitraan Strategis Bersama ${company}`,
          objective: 'Membuka presentasi dengan usulan kolaborasi yang bernilai tinggi',
          suggestedLayout: 'Hero Cover',
          layoutType: 'title_slide',
          isEdited: false,
        },
        {
          id: 'slide-2',
          slideNumber: 2,
          title: 'Peluang Pasar & Sinergi Bisnis',
          objective: 'Analisis potensi kolaborasi kedua belah pihak di segmen pasar target',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-3',
          slideNumber: 3,
          title: 'Skema Kerja Sama & Pembagian Peran',
          objective: 'Rincian hak, kewajiban, dan model operasional bersama',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-4',
          slideNumber: 4,
          title: `Kebutuhan Modal & Nilai Investasi ${structuredData.investmentValue ? `Rp ${structuredData.investmentValue}` : ''}`,
          objective: 'Ringkasan alokasi pendanaan dan struktur modal kerja',
          suggestedLayout: 'Grid 4 Metrik',
          layoutType: 'metrics_grid',
          isEdited: false,
        },
        {
          id: 'slide-5',
          slideNumber: 5,
          title: 'Proyeksi Finansial & Skema Bagi Hasil (ROI)',
          objective: 'Estimasi pengembalian modal dan pembagian dividen berkala',
          suggestedLayout: 'Grafik Finansial',
          layoutType: 'title_bullets',
          isEdited: false,
        },
        {
          id: 'slide-6',
          slideNumber: 6,
          title: 'Manajemen Risiko & Mitigasi Operasional',
          objective: 'Langkah pencegahan risiko bisnis dan kepatuhan hukum',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-7',
          slideNumber: 7,
          title: 'Profil Tim Manajemen & Rekam Jejak',
          objective: 'Kredibilitas pemimpin usaha dan pengalaman eksekusi proyek',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-8',
          slideNumber: 8,
          title: 'Tahapan Pelaksanaan & Penandatanganan MoU',
          objective: 'Timeline realisasi kemitraan dan kontak perwakilan resmi',
          suggestedLayout: 'Call to Action',
          layoutType: 'contact_closing',
          isEdited: false,
        },
      ];

    case 'laporan_ringkas':
      return [
        {
          id: 'slide-1',
          slideNumber: 1,
          title: `Laporan Kinerja & Akuntabilitas Bisnis — ${period}`,
          objective: 'Judul resmi laporan periodik dan rangkuman periode pelaporan',
          suggestedLayout: 'Hero Cover',
          layoutType: 'title_slide',
          isEdited: false,
        },
        {
          id: 'slide-2',
          slideNumber: 2,
          title: 'Ringkasan Eksekutif & Highlight Kinerja',
          objective: 'Poin-poin utama pencapaian dan kondisi umum operasional',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-3',
          slideNumber: 3,
          title: `Realisasi Omzet & Pertumbuhan Finansial ${period}`,
          objective: 'Metrik utama pendapatan kotor, volume penjualan, dan target tercapai',
          suggestedLayout: 'Grid 4 Metrik',
          layoutType: 'metrics_grid',
          isEdited: false,
        },
        {
          id: 'slide-4',
          slideNumber: 4,
          title: 'Struktur Biaya Operasional & Laba Bersih',
          objective: 'Rincian pengeluaran pokok dan hasil laba bersih usaha',
          suggestedLayout: 'Grafik Finansial',
          layoutType: 'title_bullets',
          isEdited: false,
        },
        {
          id: 'slide-5',
          slideNumber: 5,
          title: 'Pencapaian KPI Utama & Kepuasan Pelanggan',
          objective: 'Metrik performa operasional, retensi, dan efisiensi tim',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-6',
          slideNumber: 6,
          title: 'Evaluasi Kendala & Solusi Perbaikan',
          objective: 'Analisis hambatan di lapangan dan langkah tindak lanjut yang diambil',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-7',
          slideNumber: 7,
          title: 'Rencana Strategis & Target Periode Berikutnya',
          objective: 'Fokus pengembangan bisnis, perluasan pasar, dan inisiatif baru',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-8',
          slideNumber: 8,
          title: 'Catatan Penutup & Kanal Pertanggungjawaban',
          objective: 'Kontak manajemen dan sesi tanya jawab evaluasi laporan',
          suggestedLayout: 'Call to Action',
          layoutType: 'contact_closing',
          isEdited: false,
        },
      ];

    case 'company_profile':
    default:
      return [
        {
          id: 'slide-1',
          slideNumber: 1,
          title: `Profil Resmi ${company}`,
          objective: 'Memperkenalkan identitas perusahaan secara profesional dan elegan',
          suggestedLayout: 'Hero Cover',
          layoutType: 'title_slide',
          isEdited: false,
        },
        {
          id: 'slide-2',
          slideNumber: 2,
          title: 'Visi, Filosofi & Jejak Langkah Usaha',
          objective: 'Menyampaikan nilai fundamental, latar belakang, dan komitmen bisnis',
          suggestedLayout: 'Dua Kolom',
          layoutType: 'two_column',
          isEdited: false,
        },
        {
          id: 'slide-3',
          slideNumber: 3,
          title: 'Pencapaian Utama & Skala Operasional Bisnis',
          objective: 'Menampilkan data kuantitatif, kapasitas produksi, dan pertumbuhan',
          suggestedLayout: 'Grid 4 Metrik',
          layoutType: 'metrics_grid',
          isEdited: false,
        },
        {
          id: 'slide-4',
          slideNumber: 4,
          title: 'Katalog Portofolio Produk & Layanan Unggulan',
          objective: 'Menjelaskan ragam solusi dan produk yang ditawarkan kepada pelanggan',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-5',
          slideNumber: 5,
          title: 'Legalitas Usaha, Sertifikasi & Kepatuhan Standar',
          objective: 'Membuktikan keabsahan izin usaha, sertifikasi halal/SNI, dan audit mutu',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-6',
          slideNumber: 6,
          title: 'Manajemen Operasional & Tim Berpengalaman',
          objective: 'Memperkenalkan struktur kunci di balik operasional usaha',
          suggestedLayout: 'Bento Cards',
          layoutType: 'card_grid',
          isEdited: false,
        },
        {
          id: 'slide-7',
          slideNumber: 7,
          title: 'Riwayat Kinerja Finansial & Prospek Pertumbuhan',
          objective: 'Tren omzet positif dan efisiensi pengelolaan modal usaha',
          suggestedLayout: 'Grafik Finansial',
          layoutType: 'title_bullets',
          isEdited: false,
        },
        {
          id: 'slide-8',
          slideNumber: 8,
          title: 'Kemitraan Strategis, Lokasi & Kontak Resmi',
          objective: 'Mendorong audiens untuk menghubungi dan menjalin kemitraan',
          suggestedLayout: 'Call to Action',
          layoutType: 'contact_closing',
          isEdited: false,
        },
      ];
  }
}
