export const mockWorkspaceMetrics = {
  totalProjects: 12,
  monthlyTrend: "+2 bulan ini",
  tokenUsageWords: 24500,
  tokenLimitWords: 50000,
  tokenFormatted: "24.5k",
  tokenLimitFormatted: "50k",
};

export const mockProjects = [
  {
    id: "proj-1",
    title: "Company Profile – Kopi Nusantara",
    description:
      "Profil lengkap profil usaha kopi specialty, kapasitas roasting 2 ton/bulan, dan sertifikasi Halal untuk pasar ekspor & B2B.",
    status: "selesai",
    slideCount: 8,
    ratio: "16:9",
    templateName: "Company Profile",
    estimatedCost: "$0.038",
    updatedAt: "2 jam lalu",
    badgeTheme: "amber",
    accentBg: "from-amber-950/40 via-slate-900 to-slate-950",
    themeColor: "#f2a007",
    category: "Food & Beverage",
  },
  {
    id: "proj-2",
    title: "Penawaran Keripik Pedas Q3",
    description:
      "Paket bundling distributor minimarket regional Jawa Barat & Banten, skema margin grosir, dan simulasi perputaran stok.",
    status: "draft",
    slideCount: 6,
    ratio: "16:9",
    templateName: "Penawaran Produk",
    estimatedCost: "$0.024",
    updatedAt: "Kemarin",
    badgeTheme: "orange",
    accentBg: "from-orange-950/40 via-slate-900 to-slate-950",
    themeColor: "#f97316",
    category: "Retail FMCG",
  },
  {
    id: "proj-3",
    title: "Proposal Vendor Catering Mandiri",
    description:
      "Pengajuan paket makan siang harian 450 porsi pabrik Cikarang dengan menu higienis, sertifikasi Halal MUI, dan jaminan SLA ketepatan waktu.",
    status: "selesai",
    slideCount: 10,
    ratio: "16:9",
    templateName: "Proposal Kerja Sama",
    estimatedCost: "$0.046",
    updatedAt: "3 hari lalu",
    badgeTheme: "emerald",
    accentBg: "from-emerald-950/40 via-slate-900 to-slate-950",
    themeColor: "#10b981",
    category: "Jasa Katering",
  },
  {
    id: "proj-4",
    title: "Pitch Deck Pendanaan Seed Sangkar Studio",
    description:
      "Eksplorasi target pasar agensi desain kreatif UI/UX untuk scale up tim teknis, roadmap produk SaaS micro, dan proyeksi ARR 2026.",
    status: "draft",
    slideCount: 5,
    ratio: "16:9",
    templateName: "Pitch Deck Investor",
    estimatedCost: "$0.019",
    updatedAt: "5 hari lalu",
    badgeTheme: "blue",
    accentBg: "from-blue-950/40 via-slate-900 to-slate-950",
    themeColor: "#38bdf8",
    category: "Agency Digital",
  },
];
